# -*- coding: utf-8 -*-
"""
牌组数据源。所有内容集中在这里，改完跑 build_decks.py 即可重新生成 .apkg。

例句约定：目标词用 **双星号** 包起来，脚本会自动生成挖空版和高亮版。
"""

# ---------------------------------------------------------------------------
# 01 · 假朋友 · 一级警报（最高频，第 1 个月内学完）
# 字段：法语 / 英语陷阱词 / 实际意思 / 表达英语原意该用 / 例句 / 例句中文
# ---------------------------------------------------------------------------
FAUX_AMIS_1 = [
    ("actuellement", "actually", "目前、现在",
     "en fait / en réalité",
     "Je suis **actuellement** en réunion, je te rappelle.",
     "我现在正在开会，回头打给你。"),
    ("actuel / actuelle", "actual", "当前的、现今的",
     "réel, véritable",
     "La situation **actuelle** est très différente.",
     "当前的情况非常不同。"),
    ("éventuellement", "eventually", "可能、也许（不确定）",
     "finalement, à la fin",
     "Je pourrais **éventuellement** venir, mais ce n'est pas sûr.",
     "我也许能来，但不确定。"),
    ("sensible", "sensible", "敏感的、易受影响的",
     "raisonnable, sensé",
     "C'est un sujet très **sensible**, sois prudent.",
     "这是个非常敏感的话题，小心点。"),
    ("une librairie", "library", "书店",
     "une bibliothèque",
     "J'ai acheté ce roman dans une petite **librairie**.",
     "我在一家小书店买了这本小说。"),
    ("une journée", "journey", "一天（作为时段）",
     "un voyage, un trajet",
     "J'ai travaillé toute la **journée**.",
     "我工作了一整天。"),
    ("assister à", "assist", "出席、参加",
     "aider",
     "J'ai **assisté à** la conférence hier.",
     "我昨天出席了那场讲座。"),
    ("attendre", "attend", "等待",
     "assister à",
     "Je t'**attends** depuis une heure.",
     "我等你一个小时了。"),
    ("demander", "demand", "询问、请求（语气中性！）",
     "exiger",
     "Il m'a **demandé** mon avis.",
     "他问了我的意见。"),
    ("rester", "rest", "停留、留下、剩下",
     "se reposer",
     "Il ne **reste** plus de pain.",
     "已经没有面包了。"),
    ("prétendre", "pretend", "声称、断言",
     "faire semblant (de)",
     "Il **prétend** avoir tout compris.",
     "他声称自己全都懂了。"),
    ("supporter", "support", "忍受、承受",
     "soutenir, appuyer",
     "Je ne **supporte** pas le bruit.",
     "我受不了噪音。"),
    ("passer un examen", "pass an exam", "参加考试（不是通过！）",
     "réussir un examen",
     "Je **passe** mon examen lundi, j'espère le réussir.",
     "我周一参加考试，希望能通过。"),
    ("une déception", "deception", "失望",
     "une tromperie",
     "Ce film a été une vraie **déception**.",
     "这部电影真让人失望。"),
    ("décevoir", "deceive", "使失望",
     "tromper",
     "Je ne veux pas te **décevoir**.",
     "我不想让你失望。"),
    ("sympathique (sympa)", "sympathetic", "亲切的、讨人喜欢的",
     "compatissant",
     "Ta collègue est vraiment **sympa**.",
     "你同事人真好。"),
    ("une lecture", "lecture", "阅读、读物",
     "un cours, une conférence",
     "La **lecture** est mon passe-temps préféré.",
     "阅读是我最喜欢的消遣。"),
    ("la location", "location", "出租、租赁",
     "un emplacement, un lieu",
     "La **location** de l'appartement coûte 800 euros.",
     "这套公寓的租金是 800 欧元。"),
    ("un stage", "stage", "实习",
     "une scène / une étape",
     "Elle fait un **stage** de six mois à Paris.",
     "她在巴黎实习六个月。"),
    ("un collège", "college", "初中",
     "l'université",
     "Mon fils entre au **collège** cette année.",
     "我儿子今年上初中。"),
    ("une licence", "licence", "学士学位",
     "un permis",
     "Il a une **licence** de droit.",
     "他有法学学士学位。"),
]

# ---------------------------------------------------------------------------
# 02 · 假朋友 · 二级（日常高频）
# 字段：法语 / 英语陷阱词 / 实际意思 / 英语原意该用
# ---------------------------------------------------------------------------
FAUX_AMIS_2 = [
    ("la monnaie", "money", "零钱、货币", "l'argent"),
    ("un coin", "coin", "角落", "une pièce (de monnaie)"),
    ("le pain", "pain", "面包", "la douleur"),
    ("un raisin", "raisin", "葡萄", "un raisin sec"),
    ("la chair", "chair", "肉（身体的）", "une chaise"),
    ("une cave", "cave", "地窖、酒窖", "une grotte"),
    ("car", "car", "因为（连词）／ 长途大巴", "une voiture"),
    ("un bras", "bra", "手臂", "un soutien-gorge"),
    ("une veste", "vest", "外套、夹克", "un gilet"),
    ("un tissu", "tissue", "布料、织物", "un mouchoir"),
    ("une figure", "figure", "面孔、脸", "un chiffre / une silhouette"),
    ("un habit", "habit", "衣服、服装", "une habitude"),
    ("un journal", "journal", "报纸 / 日记", "une revue"),
    ("une nouvelle", "novel", "短篇小说 / 消息", "un roman"),
    ("un médecin", "medicine", "医生", "un médicament"),
    ("un crayon", "crayon", "铅笔", "un crayon de couleur"),
    ("une entrée", "entrée（美式指主菜）", "前菜、开胃菜", "le plat principal"),
    ("un agenda", "agenda", "记事本、日程本", "l'ordre du jour"),
    ("un résumé", "résumé（简历）", "摘要、总结", "un CV"),
    ("rude", "rude", "粗糙的、艰苦的", "impoli, grossier"),
    ("large", "large", "宽的", "grand"),
    ("gentil / gentille", "gentle", "善良的、好心的", "doux / douce"),
    ("la place", "place", "广场 / 座位 / 空间", "un endroit, un lieu"),
    ("rare", "rare（半熟）", "稀有的、罕见的", "saignant（牛排半熟）"),
]

# ---------------------------------------------------------------------------
# 03 · 假朋友 · 三级（会造成"意思反了"或语域事故）
# 字段：法语 / 陷阱说明 / 实际意思
# ---------------------------------------------------------------------------
FAUX_AMIS_3 = [
    ("un préservatif", "≠ preservative（防腐剂）",
     "<b>避孕套</b> —— 说错极其尴尬。防腐剂 = un conservateur"),
    ("formidable", "≠ formidable（可怕的、令人生畏的）",
     "<b>极好的、了不起的</b>。英语义 = redoutable"),
    ("terrible", "口语中常常反用",
     "既可表「糟糕的」，口语中也常表 <b>「棒极了」</b>（Ce film est terrible ! = 这片子太棒了）"),
    ("ignorer", "≠ 只表示「忽视」",
     "主要意为 <b>「不知道、不了解」</b>。J'ignore son nom = 我不知道他的名字"),
    ("achever", "≠ achieve",
     "<b>完成、了结</b>（甚至「给……最后一击」）。achieve = réaliser, accomplir"),
    ("blesser", "≠ bless",
     "<b>弄伤、伤害（也指感情）</b>。bless = bénir"),
    ("une injure", "≠ injury",
     "<b>辱骂、侮辱</b>。injury = une blessure"),
    ("user", "≠ use",
     "<b>用坏、磨损</b>。use = utiliser, se servir de"),
    ("abuser", "≠ abuse（虐待）",
     "<b>过度、滥用、做得过分</b>。Tu abuses ! = 你太过分了！"),
    ("assumer", "≠ assume（假定）",
     "<b>承担（责任、后果）</b>。assume = supposer"),
    ("une caution", "≠ caution（谨慎）",
     "<b>押金、保证金</b>。caution = la prudence"),
    ("le hasard", "≠ hazard（危险）",
     "<b>偶然、运气</b>。par hasard = 碰巧。hazard = un danger, un risque"),
    ("un préjudice", "≠ prejudice（偏见）",
     "<b>损害、损失</b>。prejudice = un préjugé"),
    ("une intoxication", "≠ 醉酒",
     "<b>中毒</b>（尤指 intoxication alimentaire 食物中毒）"),
    ("un conducteur", "≠ conductor（乐队指挥／售票员）",
     "<b>司机、驾驶员</b>。指挥 = un chef d'orchestre"),
    ("un éditeur", "≠ editor",
     "<b>出版商、出版社</b>。editor = un rédacteur (en chef)"),
    ("rentable", "≠ rentable（可出租的）",
     "<b>有盈利的、划算的</b>"),
    ("une envie", "≠ 仅 envy",
     "<b>想要、渴望</b>。avoir envie de = to want to"),
    ("une occasion", "≠ 仅 occasion",
     "<b>机会</b>；d'occasion = <b>二手的</b>"),
    ("un parent", "≠ 仅 parents",
     "<b>亲戚</b>（复数 les parents 才常指父母）"),
    ("un avertissement", "≠ advertisement",
     "<b>警告</b>。广告 = une publicité / une pub"),
    ("commander", "≠ command",
     "<b>点单、订购</b>。command = ordonner, commander（军事义才对应）"),
    ("important", "≠ 仅 important",
     "也常表 <b>「数量大的」</b>。une somme importante = 一大笔钱"),
    ("rejoindre", "≠ rejoin（重新加入）",
     "<b>与……会合、去与某人碰头</b>。Je te rejoins = 我这就过来找你"),
    ("crier", "≠ cry（哭）",
     "<b>喊叫</b>。哭 = pleurer"),
]

# ---------------------------------------------------------------------------
# 04 · 句法假朋友（英语结构直译会出错）
# 字段：英语 / 错误法语 / 正确法语 / 说明
# ---------------------------------------------------------------------------
SYNTAX = [
    ("I am eating.", "Je suis mangeant.", "Je mange.",
     "法语<b>没有进行时</b>。强调正在进行可用 être en train de + inf."),
    ("I've lived here for 3 years.", "J'ai habité ici pour 3 ans.",
     "J'habite ici depuis 3 ans.",
     "「自……以来」用<b>现在时 + depuis</b>，不是复合过去时。"),
    ("I look at the sky.", "Je regarde à le ciel.", "Je regarde le ciel.",
     "regarder / écouter / attendre / chercher / demander / payer <b>均为直接及物，不加介词</b>。"),
    ("I'm waiting for the bus.", "J'attends pour le bus.", "J'attends le bus.",
     "attendre 直接跟宾语，绝不加 pour。"),
    ("I'm looking for my keys.", "Je cherche pour mes clés.", "Je cherche mes clés.",
     "chercher 直接跟宾语。"),
    ("I enter the room.", "J'entre la pièce.", "J'entre dans la pièce.",
     "反过来：entrer <b>需要</b>介词 dans。"),
    ("I like coffee.", "J'aime café.", "J'aime le café.",
     "泛指必须加<b>定冠词</b>。"),
    ("I wash my hands.", "Je lave mes mains.", "Je me lave les mains.",
     "身体部位用<b>定冠词 + 代动词</b>，不用主有形容词。"),
    ("It is important to work.", "Il est important à travailler.",
     "Il est important de travailler.",
     "固定结构 <code>Il est + 形容词 + de + 不定式</code>。"),
    ("Do you speak French?", "Est-ce que tu fais parler français ?",
     "Parles-tu français ? / Est-ce que tu parles français ?",
     "法语<b>没有助动词 do</b>。"),
    ("People are nice here.", "Les gens est sympa ici.", "Les gens sont sympas ici.",
     "gens <b>恒为复数</b>。"),
    ("I think about it.", "Je pense de ça.", "J'y pense. / Je pense à ça.",
     "penser à = 想着某事；penser de = 对某事的看法。介词不可按英语推。"),
    ("I need it.", "J'ai besoin le.", "J'en ai besoin.",
     "avoir besoin <b>de</b> → 用代词 en 替代。"),
    ("She is a teacher.", "Elle est une professeure.", "Elle est professeure.",
     "être + 职业时<b>不加冠词</b>。"),
    ("I miss you.", "Je te manque.", "Tu me manques.",
     "manquer 的主宾<b>与英语相反</b>：思念者是间接宾语。"),
    ("Last year I went to France.",
     "L'année dernière j'ai allé en France.", "L'année dernière je suis allé(e) en France.",
     "aller 用 <b>être</b> 作助动词，且过去分词要与主语性数配合。"),
]

# 高频介词搭配（照抄英语必错）
PREPOSITIONS = [
    ("dépendre <b>de</b>", "depend <b>on</b>", "Ça dépend **de** toi.", "这取决于你。"),
    ("s'intéresser <b>à</b>", "be interested <b>in</b>", "Je m'intéresse **à** l'histoire.", "我对历史感兴趣。"),
    ("se souvenir <b>de</b>", "remember（无介词）", "Je me souviens **de** ce jour.", "我记得那一天。"),
    ("jouer <b>à</b>（运动/游戏）", "play", "Il joue **au** football.", "他踢足球。"),
    ("jouer <b>de</b>（乐器）", "play", "Elle joue **du** piano.", "她弹钢琴。"),
    ("participer <b>à</b>", "participate <b>in</b>", "Nous participons **à** ce projet.", "我们参与这个项目。"),
    ("répondre <b>à</b>", "answer（无介词）", "Réponds **à** ma question.", "回答我的问题。"),
    ("téléphoner <b>à</b>", "phone（无介词）", "Je téléphone **à** ma mère.", "我给我妈打电话。"),
    ("obéir <b>à</b>", "obey（无介词）", "Il faut obéir **aux** règles.", "必须遵守规则。"),
    ("ressembler <b>à</b>", "resemble（无介词）", "Tu ressembles **à** ton père.", "你长得像你爸。"),
    ("réussir <b>à</b>", "succeed <b>in</b>", "J'ai réussi **à** le convaincre.", "我成功说服了他。"),
    ("se moquer <b>de</b>", "make fun <b>of</b>", "Ne te moque pas **de** moi.", "别取笑我。"),
    ("avoir besoin <b>de</b>", "need（无介词）", "J'ai besoin **d'**aide.", "我需要帮助。"),
    ("s'occuper <b>de</b>", "take care <b>of</b>", "Je m'occupe **des** enfants.", "我照看孩子。"),
    ("changer <b>de</b>", "change（无介词）", "Je vais changer **de** travail.", "我要换工作。"),
    ("servir <b>à</b>（用途）", "be used <b>for</b>", "Ça sert **à** quoi ?", "这是干什么用的？"),
    ("penser <b>à</b>（想着）", "think <b>about/of</b>", "Je pense **à** toi.", "我想着你。"),
    ("rêver <b>de</b>", "dream <b>of/about</b>", "Je rêve **de** partir.", "我梦想着离开。"),
]

# ---------------------------------------------------------------------------
# 05 · 英法后缀换算公式 + 拼写侦探规则
# 字段：正面 / 背面 / 例子
# ---------------------------------------------------------------------------
SUFFIX_RULES = [
    ("英语 <b>-tion / -sion</b> → 法语？", "<b>-tion / -sion</b>（阴性 ♀，几乎不变）",
     "information → <i>l'information</i>；decision → <i>la décision</i>"),
    ("英语 <b>-ty</b> → 法语？", "<b>-té</b>（阴性 ♀）",
     "university → <i>l'université</i>；liberty → <i>la liberté</i>；quality → <i>la qualité</i>"),
    ("英语副词 <b>-ly</b> → 法语？", "<b>-ment</b>",
     "rapidly → <i>rapidement</i>；normally → <i>normalement</i>"),
    ("英语 <b>-ous</b> → 法语？", "<b>-eux / -euse</b>",
     "dangerous → <i>dangereux</i>；curious → <i>curieux</i>"),
    ("英语 <b>-ic / -ical</b> → 法语？", "<b>-ique</b>",
     "economic → <i>économique</i>；logical → <i>logique</i>"),
    ("英语 <b>-ary</b> → 法语？", "<b>-aire</b>",
     "necessary → <i>nécessaire</i>；ordinary → <i>ordinaire</i>"),
    ("英语施事 <b>-or / -er</b> → 法语？", "<b>-eur</b>（阳性 ♂）",
     "actor → <i>l'acteur</i>；director → <i>le directeur</i>"),
    ("英语 <b>-ism / -ist</b> → 法语？", "<b>-isme（♂）/ -iste（通性）</b>",
     "capitalism → <i>le capitalisme</i>；artist → <i>l'artiste</i>"),
    ("英语 <b>-ance / -ence</b> → 法语？", "<b>-ance / -ence</b>（阴性 ♀）",
     "importance → <i>l'importance</i>；difference → <i>la différence</i>"),
    ("英语动词 <b>-ate</b> → 法语？", "<b>-er</b>",
     "create → <i>créer</i>；participate → <i>participer</i>；communicate → <i>communiquer</i>"),
    ("英语 <b>-ize / -ise</b> → 法语？", "<b>-iser</b>",
     "organize → <i>organiser</i>；realize → <i>réaliser</i>"),
    ("英语 <b>-ment</b> → 法语？", "<b>-ment</b>（阳性 ♂）",
     "government → <i>le gouvernement</i>；movement → <i>le mouvement</i>"),
    ("英语 <b>-ive</b> → 法语？", "<b>-if / -ive</b>",
     "active → <i>actif / active</i>；positive → <i>positif / positive</i>"),
    ("英语 <b>-phy / -logy</b> → 法语？", "<b>-phie / -logie</b>（阴性 ♀）",
     "philosophy → <i>la philosophie</i>；biology → <i>la biologie</i>"),
    ("英语 <b>-sis</b> → 法语？", "<b>-se</b>（阴性 ♀）",
     "analysis → <i>l'analyse</i>；crisis → <i>la crise</i>"),
    ("英语 <b>-al</b> → 法语？", "<b>-el / -al</b>",
     "natural → <i>naturel</i>；national → <i>national</i>"),
]

SPELLING_RULES = [
    # 长音符 = 丢失的 s
    ("forêt", "forest", "ˆ = 丢失的 s"),
    ("hôpital", "hospital", "ˆ = 丢失的 s"),
    ("île", "isle / island", "ˆ = 丢失的 s"),
    ("château", "castle（chasteau）", "ˆ = 丢失的 s"),
    ("coût", "cost", "ˆ = 丢失的 s"),
    ("bête", "beast", "ˆ = 丢失的 s"),
    ("maître", "master", "ˆ = 丢失的 s"),
    ("tempête", "tempest", "ˆ = 丢失的 s"),
    ("honnête", "honest", "ˆ = 丢失的 s"),
    ("intérêt", "interest", "ˆ = 丢失的 s"),
    ("conquête", "conquest", "ˆ = 丢失的 s"),
    ("ancêtre", "ancestor", "ˆ = 丢失的 s"),
    ("fête", "feast / festival", "ˆ = 丢失的 s"),
    ("arrêter", "arrest（停止／逮捕）", "ˆ = 丢失的 s"),
    ("vêtement", "vestment（衣物）", "ˆ = 丢失的 s"),
    ("croûte", "crust", "ˆ = 丢失的 s"),
    # é- = s- + 辅音
    ("étudiant", "student", "词首 é- = 英语 s- + 辅音"),
    ("école", "school", "词首 é- = 英语 s- + 辅音"),
    ("état", "state", "词首 é- = 英语 s- + 辅音"),
    ("étrange", "strange", "词首 é- = 英语 s- + 辅音"),
    ("épice", "spice", "词首 é- = 英语 s- + 辅音"),
    ("éponge", "sponge", "词首 é- = 英语 s- + 辅音"),
    ("établir", "establish", "词首 é- = 英语 s- + 辅音"),
    ("épine", "spine", "词首 é- = 英语 s- + 辅音"),
    ("épouse", "spouse", "词首 é- = 英语 s- + 辅音"),
    ("écarlate", "scarlet", "词首 é- = 英语 s- + 辅音"),
    ("étoile", "star（拉丁 stella）", "词首 é- = 英语 s- + 辅音"),
    ("épaule", "shoulder（拉丁 spatula）", "词首 é- = 英语 s- + 辅音"),
]

# ---------------------------------------------------------------------------
# 06 · 阴阳性词尾规则
# 字段：词尾 / 性别 / 可靠度 / 例词 / 例外
# ---------------------------------------------------------------------------
GENDER_RULES = [
    ("-tion / -sion / -ssion", "f", "~99%", "la nation, la décision, la passion", ""),
    ("-té / -tié", "f", "~99%", "la liberté, la qualité, l'amitié", "le côté, l'été, le comité"),
    ("-ance / -ence", "f", "~95%", "la chance, la science, la différence", "le silence"),
    ("-ure", "f", "~95%", "la culture, la nature, la voiture", "le mur"),
    ("-ette", "f", "~99%", "la baguette, la cigarette", ""),
    ("-ie", "f", "~95%", "la vie, la biologie, la sortie", "le génie, le parapluie"),
    ("-esse", "f", "~99%", "la richesse, la vitesse, la jeunesse", ""),
    ("-ude / -ade", "f", "~95%", "l'habitude, la salade, la promenade", "le stade, le grade"),
    ("-eur（抽象名词）", "f", "常见", "la peur, la couleur, la douleur, la chaleur", "le bonheur, le malheur"),
    ("-ment", "m", "~99%", "le gouvernement, le moment, le bâtiment", "la jument（母马）"),
    ("-age", "m", "~90%", "le voyage, le fromage, le message",
     "<b>la plage, l'image, la page, la cage, la nage, la rage</b>"),
    ("-eau", "m", "~95%", "le bureau, le château, le bateau", "<b>l'eau ♀, la peau ♀</b>"),
    ("-isme", "m", "100%", "le capitalisme, le tourisme", ""),
    ("-oir", "m", "~95%", "le miroir, le devoir, le couloir", ""),
    ("-ier / -er", "m", "~95%", "le cahier, le quartier, le boulanger", "la mer, la cuiller"),
    ("-et / -on", "m", "~90%", "le paquet, le ballon, le bâton", "la maison, la raison, la façon"),
    ("-eur（施事者／机器）", "m", "~95%", "le professeur, le moteur, l'ordinateur", ""),
    ("英语外来词", "m", "~95%", "le week-end, le parking, le smartphone, le shopping", "la start-up"),
    ("语言名", "m", "100%", "le français, le chinois, l'anglais", ""),
    ("星期／月份／季节", "m", "100%", "le lundi, le mai, l'été, l'hiver", ""),
    ("树／金属／颜色／数字", "m", "~100%", "le chêne, le fer, le vert, le trois", ""),
]

# ---------------------------------------------------------------------------
# 07 · 高频核心词（英语无同源，你的英语优势在这里完全失效）
# 字段：法语 / 词性 / 英文释义 / 中文释义 / 例句 / 例句中文
# ---------------------------------------------------------------------------
CORE_WORDS = [
    # —— 动词 ——
    ("rester", "v.", "to stay, to remain, to be left", "停留、剩下",
     "Il **reste** encore du temps.", "还有时间。"),
    ("chercher", "v.", "to look for, to search", "找、寻找",
     "Je **cherche** mes lunettes.", "我在找我的眼镜。"),
    ("trouver", "v.", "to find; to think (opinion)", "找到；觉得",
     "Je **trouve** ça bizarre.", "我觉得这很奇怪。"),
    ("garder", "v.", "to keep; to look after", "保留、保管；照看",
     "**Garde** ça pour toi.", "这事你别说出去。"),
    ("laisser", "v.", "to leave (sth), to let", "留下；让、允许",
     "**Laisse**-moi t'expliquer.", "让我跟你解释。"),
    ("apporter", "v.", "to bring (an object)", "带来（物）",
     "**Apporte** ton ordinateur.", "把你电脑带来。"),
    ("emmener", "v.", "to take (a person) somewhere", "带走（人）",
     "Je t'**emmène** au restaurant.", "我带你去餐厅。"),
    ("essayer", "v.", "to try; to try on", "尝试；试穿",
     "**Essaie** encore une fois.", "再试一次。"),
    ("oublier", "v.", "to forget", "忘记",
     "J'ai **oublié** mon parapluie.", "我忘带伞了。"),
    ("tomber", "v.", "to fall", "掉落、跌倒",
     "Elle est **tombée** dans l'escalier.", "她在楼梯上摔倒了。"),
    ("jeter", "v.", "to throw, to throw away", "扔、丢弃",
     "Ne **jette** pas ça !", "别把这个扔了！"),
    ("ranger", "v.", "to tidy up, to put away", "整理、收好",
     "**Range** ta chambre.", "把你房间收拾一下。"),
    ("allumer / éteindre", "v.", "to turn on / to turn off", "打开／关掉（电器、灯）",
     "**Éteins** la lumière en sortant.", "出去时把灯关了。"),
    ("gagner", "v.", "to win; to earn", "赢；赚",
     "Elle **gagne** bien sa vie.", "她收入不错。"),
    ("choisir", "v.", "to choose", "选择",
     "Il faut **choisir** maintenant.", "现在必须做选择。"),
    ("empêcher", "v.", "to prevent, to stop (sb from)", "阻止、妨碍",
     "Rien ne t'**empêche** d'essayer.", "没什么能阻止你去试。"),
    ("éviter", "v.", "to avoid", "避免",
     "J'**évite** les heures de pointe.", "我避开高峰时段。"),
    ("atteindre", "v.", "to reach, to attain", "达到、抵达",
     "Nous avons **atteint** notre objectif.", "我们达到了目标。"),
    ("gérer", "v.", "to manage, to handle", "管理、处理",
     "Je **gère** la situation.", "我来处理这个情况。"),
    ("plaire (à)", "v.", "to please, to be liked by", "使喜欢（主宾与英语相反）",
     "Ce film m'a beaucoup **plu**.", "我很喜欢这部电影。"),
    ("manquer (à)", "v.", "to miss (sb); to lack", "思念（主宾相反）；缺少",
     "Tu me **manques**.", "我想你。"),
    ("suffire", "v.", "to be enough", "足够",
     "Ça **suffit** !", "够了！"),
    ("se débrouiller", "v.", "to manage, to cope", "自己应付、想办法",
     "Je me **débrouille** en français.", "我法语还应付得来。"),
    ("se rendre compte (de)", "v.", "to realize", "意识到",
     "Je ne m'étais pas **rendu compte**.", "我之前没意识到。"),
    ("falloir (il faut)", "v.", "to be necessary, must", "必须、需要（无人称）",
     "Il **faut** partir maintenant.", "现在必须走了。"),
    ("valoir (ça vaut)", "v.", "to be worth", "值得、价值",
     "Ça **vaut** le coup.", "这值得一试。"),
    ("s'agir (il s'agit de)", "v.", "to be about, to be a matter of", "涉及、关于",
     "Il **s'agit** d'un malentendu.", "这是个误会。"),
    ("appartenir (à)", "v.", "to belong to", "属于",
     "Ce livre **appartient** à Marie.", "这本书是玛丽的。"),
    # —— 副词 / 连接词（B2 写作与口语的关键）——
    ("encore", "adv.", "still; again; more", "还、仍然；再；更",
     "Tu es **encore** là ?", "你还在这儿？"),
    ("déjà", "adv.", "already", "已经",
     "J'ai **déjà** mangé.", "我已经吃过了。"),
    ("plutôt", "adv.", "rather, quite; instead", "宁可、相当；而是",
     "C'est **plutôt** difficile.", "这相当难。"),
    ("quand même", "loc.", "still, anyway, all the same", "还是、仍然（口语高频）",
     "C'est cher, mais je le prends **quand même**.", "有点贵，但我还是买。"),
    ("d'ailleurs", "loc.", "besides, by the way, moreover", "再说、顺便一提",
     "**D'ailleurs**, je voulais t'en parler.", "再说，我本来就想跟你聊这个。"),
    ("du coup", "loc.", "so, as a result（口语）", "结果、于是（口语极高频）",
     "Il pleuvait, **du coup** on est restés.", "下雨了，结果我们就没走。"),
    ("désormais", "adv.", "from now on, henceforth", "从今以后（书面）",
     "**Désormais**, tout sera différent.", "从今以后一切都会不同。"),
    ("toutefois", "adv.", "however, nevertheless", "然而（书面）",
     "Ce projet est ambitieux ; **toutefois**, il reste réalisable.",
     "这个项目雄心勃勃，然而仍然可行。"),
    ("néanmoins", "adv.", "nevertheless, nonetheless", "尽管如此（B2 写作必备）",
     "Les résultats sont modestes ; **néanmoins**, ils sont encourageants.",
     "结果不算显著，但仍令人鼓舞。"),
    ("en revanche", "loc.", "on the other hand, by contrast", "相反、另一方面",
     "Le prix est élevé ; **en revanche**, la qualité est excellente.",
     "价格偏高，但质量极好。"),
    ("or", "conj.", "now, yet (introduces a turn in argument)", "然而、可是（论证转折，B2 常见）",
     "Tout semblait réglé. **Or**, un problème est apparu.",
     "一切似乎都解决了。然而，一个问题出现了。"),
    ("certes", "adv.", "admittedly, granted（让步）", "诚然、固然（让步开场）",
     "**Certes**, c'est coûteux, mais c'est nécessaire.",
     "诚然这很贵，但很有必要。"),
    ("en effet", "loc.", "indeed, in fact (confirms/explains)", "确实、事实上（用于印证）",
     "Il n'est pas venu ; **en effet**, il était malade.",
     "他没来；事实上他病了。"),
    ("voire", "adv.", "or even, indeed", "甚至（书面递进）",
     "C'est difficile, **voire** impossible.", "这很难，甚至不可能。"),
    ("tandis que", "conj.", "whereas, while", "而、与此同时（对比）",
     "Il travaille, **tandis que** son frère s'amuse.",
     "他在工作，而他弟弟在玩。"),
    ("alors que", "conj.", "whereas; while", "尽管、而（对比）",
     "Il est sorti **alors qu'**il pleuvait.", "尽管下着雨他还是出门了。"),
    ("dès que", "conj.", "as soon as", "一……就……",
     "Appelle-moi **dès que** tu arrives.", "你一到就给我打电话。"),
    ("afin de / afin que", "loc.", "in order to / so that", "为了（书面）",
     "Il travaille dur **afin de** réussir.", "他努力工作以求成功。"),
    ("sinon", "conj.", "otherwise, or else", "否则",
     "Dépêche-toi, **sinon** on va être en retard.", "快点，否则我们要迟到了。"),
    ("autant", "adv.", "as much, so much", "同样多、如此多",
     "Je n'ai jamais **autant** travaillé.", "我从没这么努力过。"),
    ("tellement", "adv.", "so, so much", "如此、这么",
     "Il fait **tellement** chaud !", "太热了！"),
    ("à peine", "loc.", "hardly, barely", "几乎不、刚刚",
     "Je l'ai **à peine** vu.", "我几乎没看见他。"),
    # —— 名词 / 形容词 ——
    ("un truc", "n.m.", "thing, thingy（口语）", "东西、玩意儿（口语万能词）",
     "C'est quoi ce **truc** ?", "这是什么玩意儿？"),
    ("un endroit", "n.m.", "place, spot", "地方",
     "C'est un **endroit** magnifique.", "这地方真美。"),
    ("le milieu", "n.m.", "middle; environment, circle", "中间；环境、圈子",
     "au **milieu** de la nuit", "在半夜"),
    ("la plupart (de)", "n.f.", "most (of)", "大部分",
     "**La plupart** des gens sont d'accord.", "大部分人都同意。"),
    ("un souci", "n.m.", "worry, problem", "烦恼、问题",
     "Pas de **souci** !", "没问题！"),
    ("le boulot", "n.m.", "job, work（口语）", "工作（口语）",
     "J'ai beaucoup de **boulot**.", "我活儿很多。"),
    ("chaque / chacun", "adj./pron.", "each / each one", "每个／每一个",
     "**Chacun** fait ce qu'il veut.", "各人做各人的事。"),
    ("pareil / pareille", "adj.", "the same, similar", "一样的",
     "C'est **pareil** pour moi.", "对我来说都一样。"),
    ("propre", "adj.", "clean; (before noun) own", "干净的；（前置）自己的",
     "sa **propre** voiture / une chemise **propre**", "他自己的车／一件干净衬衫"),
    ("épais / épaisse", "adj.", "thick", "厚的",
     "un livre très **épais**", "一本很厚的书"),
    ("lourd / léger", "adj.", "heavy / light", "重的／轻的",
     "Ce sac est trop **lourd**.", "这包太重了。"),
    ("vide / plein", "adj.", "empty / full", "空的／满的",
     "La salle est presque **vide**.", "大厅几乎是空的。"),
    ("doux / douce", "adj.", "soft, gentle, mild, sweet", "柔和的、温和的",
     "une voix très **douce**", "一个非常温柔的声音"),
    ("n'importe quoi", "loc.", "nonsense; anything at all", "胡说八道；随便什么",
     "Tu dis **n'importe quoi** !", "你在胡说八道！"),
    ("ça marche", "loc.", "it works; OK, deal（口语）", "行、可以（口语）",
     "On se voit à 8h ? — **Ça marche** !", "八点见？——行！"),
    ("en fait", "loc.", "actually, in fact", "其实、实际上（注意：不是 actuellement）",
     "**En fait**, je ne savais pas.", "其实我并不知道。"),
    ("c'est-à-dire", "loc.", "that is to say, i.e.", "也就是说",
     "Demain, **c'est-à-dire** lundi.", "明天，也就是周一。"),
]
