# -*- coding: utf-8 -*-
"""
牌组数据源。改完这个文件后跑 build_decks.py 重新生成 .apkg。

每条词汇的字段：
    fr    法语词条（名词务必带冠词 un/une，脚本据此判断阴阳性并着色）
    pos   词性代码，见下表
    gram  语法细节：动词写组别/助动词/过去分词/关键变位；名词写复数；形容词写阴性形式
    en    英文释义（优先，英法之间是直接映射）
    zh    中文释义
    ex    例句，目标词用 **双星号** 包住 → 脚本自动生成挖空版与高亮版
    exzh  例句中文

词性代码 pos：
    n.m.     名词·阳性        n.f.     名词·阴性
    v.       动词             v.pron.  代动词
    v.imp.   无人称动词       adj.     形容词
    adv.     副词             conj.    连词
    prép.    介词             loc.     固定短语
    expr.    惯用表达         pron.    代词
"""

# ---------------------------------------------------------------------------
# 01 · 假朋友 · 一级警报（最高频，第 1 个月内学完）
# 额外字段：trap 英语陷阱词 / correct 表达英语原意该用的法语
# ---------------------------------------------------------------------------
FAUX_AMIS_1 = [
    dict(fr="actuellement", pos="adv.", gram="由 actuel + -ment 构成",
         trap="actually", correct="en fait / en réalité",
         en="currently, at the moment", zh="目前、现在",
         ex="Je suis **actuellement** en réunion, je te rappelle.",
         exzh="我现在正在开会，回头打给你。"),
    dict(fr="actuel / actuelle", pos="adj.", gram="阴性 actuelle · 复数 actuels / actuelles · 一般后置",
         trap="actual", correct="réel / véritable",
         en="current, present-day", zh="当前的、现今的",
         ex="La situation **actuelle** est très différente.",
         exzh="当前的情况非常不同。"),
    dict(fr="éventuellement", pos="adv.", gram="由 éventuel + -ment 构成",
         trap="eventually", correct="finalement / à la fin",
         en="possibly, if need be", zh="可能、也许（不确定）",
         ex="Je pourrais **éventuellement** venir, mais ce n'est pas sûr.",
         exzh="我也许能来，但不确定。"),
    dict(fr="sensible", pos="adj.", gram="阴阳性同形 · 复数 sensibles",
         trap="sensible", correct="raisonnable / sensé",
         en="sensitive", zh="敏感的、易受影响的",
         ex="C'est un sujet très **sensible**, sois prudent.",
         exzh="这是个非常敏感的话题，小心点。"),
    dict(fr="une librairie", pos="n.f.", gram="复数 des librairies · 书商 un(e) libraire",
         trap="library", correct="une bibliothèque",
         en="bookshop, bookstore", zh="书店",
         ex="J'ai acheté ce roman dans une petite **librairie**.",
         exzh="我在一家小书店买了这本小说。"),
    dict(fr="une journée", pos="n.f.",
         gram="复数 des journées · 对比 un jour（日子/单位），journée 强调「一整天的时段」",
         trap="journey", correct="un voyage / un trajet",
         en="day (as a span of time)", zh="一天（作为时段）",
         ex="J'ai travaillé toute la **journée**.",
         exzh="我工作了一整天。"),
    dict(fr="assister à", pos="v.", gram="第1组 -er · 助动词 avoir · p.p. assisté · 必须带介词 à",
         trap="assist", correct="aider",
         en="to attend (an event)", zh="出席、参加",
         ex="J'ai **assisté à** la conférence hier.",
         exzh="我昨天出席了那场讲座。"),
    dict(fr="attendre", pos="v.",
         gram="第3组 · 助动词 avoir · p.p. attendu · j'attends, nous attendons · <b>直接及物，不加介词</b>",
         trap="attend", correct="assister à",
         en="to wait (for)", zh="等待",
         ex="Je t'**attends** depuis une heure.",
         exzh="我等你一个小时了。"),
    dict(fr="demander", pos="v.",
         gram="第1组 -er · 助动词 avoir · p.p. demandé · demander qch à qn",
         trap="demand", correct="exiger",
         en="to ask (for) — neutral in tone", zh="询问、请求（语气中性！）",
         ex="Il m'a **demandé** mon avis.",
         exzh="他问了我的意见。"),
    dict(fr="rester", pos="v.",
         gram="第1组 -er · <b>助动词 être</b> · p.p. resté(e)(s) · je suis resté(e)",
         trap="rest", correct="se reposer",
         en="to stay, to remain, to be left", zh="停留、留下、剩下",
         ex="Il ne **reste** plus de pain.",
         exzh="已经没有面包了。"),
    dict(fr="prétendre", pos="v.",
         gram="第3组 · 助动词 avoir · p.p. prétendu · je prétends, nous prétendons",
         trap="pretend", correct="faire semblant (de)",
         en="to claim, to assert", zh="声称、断言",
         ex="Il **prétend** avoir tout compris.",
         exzh="他声称自己全都懂了。"),
    dict(fr="supporter", pos="v.", gram="第1组 -er · 助动词 avoir · p.p. supporté",
         trap="support", correct="soutenir / appuyer",
         en="to bear, to put up with", zh="忍受、承受",
         ex="Je ne **supporte** pas le bruit.",
         exzh="我受不了噪音。"),
    dict(fr="passer un examen", pos="expr.",
         gram="passer 第1组 · 助动词 avoir（此义）· <b>通过</b>考试 = réussir un examen",
         trap="to pass an exam", correct="réussir un examen",
         en="to take / sit an exam (NOT to pass)", zh="参加考试（不是通过！）",
         ex="Je **passe** mon examen lundi, j'espère le réussir.",
         exzh="我周一参加考试，希望能通过。"),
    dict(fr="une déception", pos="n.f.", gram="复数 des déceptions · 动词 décevoir",
         trap="deception", correct="une tromperie",
         en="disappointment", zh="失望",
         ex="Ce film a été une vraie **déception**.",
         exzh="这部电影真让人失望。"),
    dict(fr="décevoir", pos="v.",
         gram="第3组 · 助动词 avoir · p.p. <b>déçu</b> · je déçois, nous décevons",
         trap="to deceive", correct="tromper",
         en="to disappoint", zh="使失望",
         ex="Je ne veux pas te **décevoir**.",
         exzh="我不想让你失望。"),
    dict(fr="sympathique", pos="adj.",
         gram="阴阳性同形 · 复数 sympathiques · 口语缩略 <b>sympa</b>（不分阴阳性，复数 sympas）",
         trap="sympathetic", correct="compatissant",
         en="nice, likeable", zh="亲切的、讨人喜欢的",
         ex="Ta collègue est vraiment **sympathique**.",
         exzh="你同事人真好。"),
    dict(fr="une lecture", pos="n.f.", gram="复数 des lectures · 动词 lire",
         trap="lecture", correct="un cours / une conférence",
         en="reading", zh="阅读、读物",
         ex="La **lecture** est mon passe-temps préféré.",
         exzh="阅读是我最喜欢的消遣。"),
    dict(fr="la location", pos="n.f.", gram="复数 des locations · 动词 louer（出租／租用）",
         trap="location", correct="un emplacement / un lieu",
         en="renting, rental", zh="出租、租赁",
         ex="La **location** de l'appartement coûte 800 euros.",
         exzh="这套公寓的租金是 800 欧元。"),
    dict(fr="un stage", pos="n.m.", gram="复数 des stages · 实习生 un(e) stagiaire",
         trap="stage", correct="une scène（舞台）／ une étape（阶段）",
         en="internship, training placement", zh="实习",
         ex="Elle fait un **stage** de six mois à Paris.",
         exzh="她在巴黎实习六个月。"),
    dict(fr="un collège", pos="n.m.",
         gram="复数 des collèges · 法国学制：collège 初中(11–15岁) → lycée 高中 → université 大学",
         trap="college", correct="l'université",
         en="secondary / middle school", zh="初中",
         ex="Mon fils entre au **collège** cette année.",
         exzh="我儿子今年上初中。"),
    dict(fr="une licence", pos="n.f.",
         gram="复数 des licences · 法国学位：licence 学士 → master 硕士 → doctorat 博士",
         trap="licence / license", correct="un permis",
         en="bachelor's degree", zh="学士学位",
         ex="Il a une **licence** de droit.",
         exzh="他有法学学士学位。"),
]

# ---------------------------------------------------------------------------
# 02 · 假朋友 · 二级（日常高频）
# ---------------------------------------------------------------------------
FAUX_AMIS_2 = [
    dict(fr="la monnaie", pos="n.f.", gram="复数 des monnaies · 对比 l'argent（钱，泛指）",
         trap="money", correct="l'argent",
         en="change (coins); currency", zh="零钱、货币",
         ex="Vous avez la **monnaie** de dix euros ?", exzh="你有十欧的零钱吗？"),
    dict(fr="un coin", pos="n.m.", gram="复数 des coins · au coin de la rue = 在街角",
         trap="coin", correct="une pièce (de monnaie)",
         en="corner", zh="角落",
         ex="La boulangerie est au **coin** de la rue.", exzh="面包店在街角。"),
    dict(fr="le pain", pos="n.m.", gram="复数 des pains · un pain = 一个面包；du pain = 一些面包",
         trap="pain", correct="la douleur",
         en="bread", zh="面包",
         ex="Je vais acheter du **pain**.", exzh="我去买点面包。"),
    dict(fr="un raisin", pos="n.m.", gram="复数 des raisins · 葡萄干 = un raisin sec",
         trap="raisin", correct="un raisin sec",
         en="grape", zh="葡萄",
         ex="J'adore le **raisin** blanc.", exzh="我很喜欢白葡萄。"),
    dict(fr="la chair", pos="n.f.", gram="与 la chaise（椅子）只差一个字母 · chair de poule = 鸡皮疙瘩",
         trap="chair", correct="une chaise",
         en="flesh", zh="肉（身体的）",
         ex="Il avait la **chair** de poule.", exzh="他起了鸡皮疙瘩。"),
    dict(fr="une cave", pos="n.f.", gram="复数 des caves · 洞穴 = une grotte",
         trap="cave", correct="une grotte",
         en="cellar, basement", zh="地窖、酒窖",
         ex="Le vin est à la **cave**.", exzh="酒在地窖里。"),
    dict(fr="car", pos="conj. / n.m.",
         gram="① 连词 = 因为（书面，近 parce que）② un car = 长途大巴，复数 des cars",
         trap="car", correct="une voiture",
         en="① for, because　② coach, bus", zh="① 因为（连词）② 长途大巴",
         ex="Je reste chez moi, **car** il pleut.", exzh="我待在家，因为下雨了。"),
    dict(fr="un bras", pos="n.m.", gram="<b>复数 des bras</b>（词尾已有 s，不变）· 词尾 s 不发音",
         trap="bra", correct="un soutien-gorge",
         en="arm", zh="手臂",
         ex="Il s'est cassé le **bras**.", exzh="他摔断了胳膊。"),
    dict(fr="une veste", pos="n.f.", gram="复数 des vestes · 背心 = un gilet",
         trap="vest", correct="un gilet",
         en="jacket", zh="外套、夹克",
         ex="Mets ta **veste**, il fait froid.", exzh="穿上外套，天冷。"),
    dict(fr="un tissu", pos="n.m.", gram="复数 des tissus · 纸巾 = un mouchoir (en papier)",
         trap="tissue", correct="un mouchoir",
         en="fabric, cloth", zh="布料、织物",
         ex="Ce **tissu** est très doux.", exzh="这块布料很柔软。"),
    dict(fr="une figure", pos="n.f.", gram="复数 des figures · 也指「图形」· 数字 = un chiffre",
         trap="figure", correct="un chiffre / une silhouette",
         en="face", zh="面孔、脸",
         ex="Elle a une jolie **figure**.", exzh="她有一张漂亮的脸。"),
    dict(fr="un habit", pos="n.m.", gram="<b>常用复数 des habits</b> 表「衣服」· 习惯 = une habitude",
         trap="habit", correct="une habitude",
         en="garment; (pl.) clothes", zh="衣服、服装",
         ex="Range tes **habits** !", exzh="把你衣服收好！"),
    dict(fr="un journal", pos="n.m.", gram="<b>复数 des journaux</b>（-al → -aux）· 也指日记",
         trap="journal", correct="une revue（学术期刊）",
         en="newspaper; diary", zh="报纸 / 日记",
         ex="Je lis le **journal** tous les matins.", exzh="我每天早上看报纸。"),
    dict(fr="une nouvelle", pos="n.f.",
         gram="复数 des nouvelles（复数常指「消息」）· 长篇小说 = un roman",
         trap="novel", correct="un roman",
         en="short story; piece of news", zh="短篇小说 / 消息",
         ex="J'ai une bonne **nouvelle** !", exzh="我有个好消息！"),
    dict(fr="un médecin", pos="n.m.",
         gram="复数 des médecins · 药 = un médicament · 医学 = la médecine",
         trap="medicine", correct="un médicament",
         en="doctor, physician", zh="医生",
         ex="Je dois voir un **médecin**.", exzh="我得去看医生。"),
    dict(fr="un crayon", pos="n.m.", gram="复数 des crayons · 蜡笔 = un crayon de couleur",
         trap="crayon", correct="un crayon de couleur",
         en="pencil", zh="铅笔",
         ex="Écris au **crayon**, pas au stylo.", exzh="用铅笔写，别用钢笔。"),
    dict(fr="une entrée", pos="n.f.",
         gram="复数 des entrées · 法餐顺序：entrée 前菜 → plat 主菜 → dessert 甜点",
         trap="entrée（美式指主菜）", correct="le plat principal",
         en="starter, appetizer; entrance", zh="前菜、开胃菜；入口",
         ex="Comme **entrée**, je prends une salade.", exzh="前菜我要一份沙拉。"),
    dict(fr="un agenda", pos="n.m.", gram="复数 des agendas · 会议议程 = l'ordre du jour",
         trap="agenda", correct="l'ordre du jour",
         en="diary, planner", zh="记事本、日程本",
         ex="Note-le dans ton **agenda**.", exzh="记到你日程本上。"),
    dict(fr="un résumé", pos="n.m.", gram="复数 des résumés · 简历 = un CV",
         trap="résumé（简历）", correct="un CV",
         en="summary, abstract", zh="摘要、总结",
         ex="Fais-moi un **résumé** de l'article.", exzh="给我总结一下这篇文章。"),
    dict(fr="rude", pos="adj.", gram="阴阳性同形 · 复数 rudes · 粗鲁 = impoli / grossier",
         trap="rude", correct="impoli / grossier",
         en="harsh, tough, rough", zh="粗糙的、艰苦的",
         ex="L'hiver a été **rude** cette année.", exzh="今年冬天很严酷。"),
    dict(fr="large", pos="adj.", gram="阴阳性同形 · 复数 larges · 大的 = grand",
         trap="large", correct="grand",
         en="wide, broad", zh="宽的",
         ex="La route est très **large** ici.", exzh="这里的路很宽。"),
    dict(fr="gentil / gentille", pos="adj.",
         gram="<b>阴性 gentille</b> · 复数 gentils / gentilles · 温柔 = doux / douce",
         trap="gentle", correct="doux / douce",
         en="kind, nice", zh="善良的、好心的",
         ex="C'est très **gentil** de ta part.", exzh="你真是太好心了。"),
    dict(fr="la place", pos="n.f.", gram="复数 des places · 三个常用义：广场 / 座位 / 空间",
         trap="place", correct="un endroit / un lieu",
         en="square; seat; room, space", zh="广场 / 座位 / 空间",
         ex="Il n'y a plus de **place** dans la voiture.", exzh="车里没位置了。"),
    dict(fr="rare", pos="adj.", gram="阴阳性同形 · 复数 rares · 牛排三分熟 = saignant",
         trap="rare（牛排半熟）", correct="saignant",
         en="rare, scarce", zh="稀有的、罕见的",
         ex="C'est une espèce très **rare**.", exzh="这是一个非常稀有的物种。"),
]

# ---------------------------------------------------------------------------
# 03 · 假朋友 · 三级（会造成"意思反了"或语域事故）
# ---------------------------------------------------------------------------
FAUX_AMIS_3 = [
    dict(fr="un préservatif", pos="n.m.", gram="复数 des préservatifs · 防腐剂 = un conservateur",
         trap="≠ preservative（防腐剂）", correct="un conservateur",
         en="condom", zh="避孕套 —— 说错极其尴尬",
         ex="Ce produit est sans **conservateurs**.", exzh="这个产品不含防腐剂。"),
    dict(fr="formidable", pos="adj.", gram="阴阳性同形 · 复数 formidables · 可怕的 = redoutable",
         trap="≠ formidable（可怕的、令人生畏的）", correct="redoutable",
         en="great, wonderful", zh="极好的、了不起的",
         ex="C'est une **formidable** nouvelle !", exzh="这真是个了不起的好消息！"),
    dict(fr="terrible", pos="adj.", gram="阴阳性同形 · <b>口语中常反用为褒义</b>",
         trap="口语中常常反用", correct="affreux（真正的「糟糕」）",
         en="terrible; (colloq.) awesome", zh="既可表「糟糕的」，口语中也常表「棒极了」",
         ex="Ce film est **terrible** !", exzh="这片子太棒了！（口语褒义）"),
    dict(fr="ignorer", pos="v.", gram="第1组 -er · 助动词 avoir · p.p. ignoré",
         trap="≠ 只表示「忽视」", correct="ne pas tenir compte de（忽视）",
         en="to not know, to be unaware of", zh="主要意为「不知道、不了解」",
         ex="J'**ignore** son nom.", exzh="我不知道他叫什么。"),
    dict(fr="achever", pos="v.",
         gram="第1组 -er · 助动词 avoir · p.p. achevé · <b>j'achève</b>, nous achevons（e→è）",
         trap="≠ achieve", correct="réaliser / accomplir",
         en="to complete, to finish off", zh="完成、了结（甚至「给……最后一击」）",
         ex="Il a **achevé** son roman.", exzh="他完成了他的小说。"),
    dict(fr="blesser", pos="v.", gram="第1组 -er · 助动词 avoir · p.p. blessé",
         trap="≠ bless", correct="bénir",
         en="to injure, to hurt (also emotionally)", zh="弄伤、伤害（也指感情）",
         ex="Tes paroles m'ont **blessé**.", exzh="你的话伤到我了。"),
    dict(fr="une injure", pos="n.f.", gram="复数 des injures · 伤口 = une blessure",
         trap="≠ injury", correct="une blessure",
         en="insult, abuse (verbal)", zh="辱骂、侮辱",
         ex="Il a crié des **injures**.", exzh="他大声辱骂。"),
    dict(fr="user", pos="v.", gram="第1组 -er · 助动词 avoir · p.p. usé · user de qch = 使用某物",
         trap="≠ use", correct="utiliser / se servir de",
         en="to wear out", zh="用坏、磨损",
         ex="J'ai **usé** mes chaussures.", exzh="我把鞋子穿坏了。"),
    dict(fr="abuser", pos="v.", gram="第1组 -er · 助动词 avoir · p.p. abusé · abuser <b>de</b> qch",
         trap="≠ abuse（虐待）", correct="maltraiter",
         en="to overdo it, to go too far", zh="过度、滥用、做得过分",
         ex="Tu **abuses** vraiment !", exzh="你真是太过分了！"),
    dict(fr="assumer", pos="v.", gram="第1组 -er · 助动词 avoir · p.p. assumé",
         trap="≠ assume（假定）", correct="supposer",
         en="to take on, to accept (responsibility)", zh="承担（责任、后果）",
         ex="Il **assume** ses erreurs.", exzh="他承担自己的错误。"),
    dict(fr="une caution", pos="n.f.", gram="复数 des cautions · 谨慎 = la prudence",
         trap="≠ caution（谨慎）", correct="la prudence",
         en="deposit, security", zh="押金、保证金",
         ex="Il faut verser une **caution** de deux mois.", exzh="要交两个月的押金。"),
    dict(fr="le hasard", pos="n.m.",
         gram="<b>嘘音 h</b>：说 le hasard，不省音 · par hasard = 碰巧 · 危险 = un danger",
         trap="≠ hazard（危险）", correct="un danger / un risque",
         en="chance, coincidence", zh="偶然、运气",
         ex="Je l'ai rencontré par **hasard**.", exzh="我碰巧遇到了他。"),
    dict(fr="un préjudice", pos="n.m.", gram="复数 des préjudices · 偏见 = un préjugé",
         trap="≠ prejudice（偏见）", correct="un préjugé",
         en="harm, damage, prejudice (legal)", zh="损害、损失",
         ex="Cela lui a causé un grave **préjudice**.", exzh="这给他造成了严重损失。"),
    dict(fr="une intoxication", pos="n.f.",
         gram="最常见搭配 intoxication <b>alimentaire</b>（食物中毒）· 醉酒 = l'ivresse",
         trap="≠ 醉酒", correct="l'ivresse",
         en="poisoning (esp. food poisoning)", zh="中毒",
         ex="Il a eu une **intoxication** alimentaire.", exzh="他食物中毒了。"),
    dict(fr="un conducteur", pos="n.m.",
         gram="<b>阴性 une conductrice</b> · 复数 des conducteurs · 乐队指挥 = un chef d'orchestre",
         trap="≠ conductor（乐队指挥／售票员）", correct="un chef d'orchestre",
         en="driver", zh="司机、驾驶员",
         ex="Le **conducteur** a freiné brusquement.", exzh="司机猛地刹车。"),
    dict(fr="un éditeur", pos="n.m.",
         gram="<b>阴性 une éditrice</b> · 编辑 = un rédacteur (en chef)",
         trap="≠ editor", correct="un rédacteur",
         en="publisher", zh="出版商、出版社",
         ex="Mon **éditeur** attend le manuscrit.", exzh="我的出版商在等稿子。"),
    dict(fr="rentable", pos="adj.", gram="阴阳性同形 · 复数 rentables · 可出租的 = louable",
         trap="≠ rentable（可出租的）", correct="louable",
         en="profitable, worthwhile", zh="有盈利的、划算的",
         ex="Ce projet n'est pas **rentable**.", exzh="这个项目不赚钱。"),
    dict(fr="une envie", pos="n.f.", gram="<b>avoir envie de</b> + 名词/不定式 = 想要",
         trap="≠ 仅 envy", correct="la jalousie（嫉妒）",
         en="desire, urge; envy", zh="想要、渴望",
         ex="J'ai **envie** d'un café.", exzh="我想喝杯咖啡。"),
    dict(fr="une occasion", pos="n.f.",
         gram="复数 des occasions · <b>d'occasion</b> = 二手的（une voiture d'occasion）",
         trap="≠ 仅 occasion", correct="—",
         en="opportunity; second-hand", zh="机会；二手的",
         ex="C'est une bonne **occasion** de pratiquer.", exzh="这是练习的好机会。"),
    dict(fr="un parent", pos="n.m.",
         gram="阴性 une parente · <b>单数常指「亲戚」</b>，复数 les parents 才常指父母",
         trap="≠ 仅 parents", correct="—",
         en="relative; (pl.) parents", zh="亲戚；（复数）父母",
         ex="C'est un **parent** éloigné.", exzh="这是个远亲。"),
    dict(fr="un avertissement", pos="n.m.", gram="复数 des avertissements · 动词 avertir（第2组）",
         trap="≠ advertisement", correct="une publicité / une pub",
         en="warning", zh="警告",
         ex="Il a reçu un **avertissement**.", exzh="他收到了一个警告。"),
    dict(fr="commander", pos="v.", gram="第1组 -er · 助动词 avoir · p.p. commandé",
         trap="≠ command（命令）", correct="ordonner",
         en="to order (food, goods)", zh="点单、订购",
         ex="J'ai **commandé** une pizza.", exzh="我点了一个披萨。"),
    dict(fr="important / importante", pos="adj.",
         gram="阴性 importante · <b>也表「数量大的」</b>（une somme importante = 一大笔钱）",
         trap="≠ 仅 important", correct="—",
         en="important; large, considerable", zh="重要的；数量大的",
         ex="Il a dépensé une somme **importante**.", exzh="他花了一大笔钱。"),
    dict(fr="rejoindre", pos="v.",
         gram="第3组 · 助动词 avoir · p.p. <b>rejoint</b> · je rejoins, nous rejoignons",
         trap="≠ rejoin（重新加入）", correct="réintégrer",
         en="to join, to meet up with", zh="与……会合、去找某人",
         ex="Je te **rejoins** dans dix minutes.", exzh="我十分钟后来找你。"),
    dict(fr="crier", pos="v.", gram="第1组 -er · 助动词 avoir · p.p. crié · 哭 = pleurer",
         trap="≠ cry（哭）", correct="pleurer",
         en="to shout, to scream", zh="喊叫",
         ex="Ne **crie** pas, je t'entends.", exzh="别喊，我听得见。"),
]

# ---------------------------------------------------------------------------
# 04 · 句法假朋友（英语结构直译会出错）
# ---------------------------------------------------------------------------
SYNTAX = [
    ("I am eating.", "Je suis mangeant.", "Je mange.",
     "法语<b>没有进行时</b>。强调正在进行用 <i>être en train de</i> + 不定式。"),
    ("I've lived here for 3 years.", "J'ai habité ici pour 3 ans.",
     "J'habite ici depuis 3 ans.",
     "「自……以来」用<b>现在时 + depuis</b>，不是复合过去时。"),
    ("I look at the sky.", "Je regarde à le ciel.", "Je regarde le ciel.",
     "regarder / écouter / attendre / chercher / demander / payer <b>均为直接及物，不加介词</b>。"),
    ("I'm waiting for the bus.", "J'attends pour le bus.", "J'attends le bus.",
     "attendre 直接跟宾语，绝不加 pour。"),
    ("I'm looking for my keys.", "Je cherche pour mes clés.", "Je cherche mes clés.",
     "chercher 直接跟宾语。"),
    ("I enter the room.", "J'entre la pièce.", "J'entre dans la pièce.",
     "反过来：entrer <b>需要</b>介词 dans。"),
    ("I like coffee.", "J'aime café.", "J'aime le café.",
     "泛指必须加<b>定冠词</b>。"),
    ("I wash my hands.", "Je lave mes mains.", "Je me lave les mains.",
     "身体部位用<b>定冠词 + 代动词</b>，不用主有形容词。"),
    ("It is important to work.", "Il est important à travailler.",
     "Il est important de travailler.",
     "固定结构 <code>Il est + 形容词 + de + 不定式</code>。"),
    ("Do you speak French?", "Est-ce que tu fais parler français ?",
     "Parles-tu français ?",
     "法语<b>没有助动词 do</b>，靠倒装或 est-ce que 提问。"),
    ("People are nice here.", "Les gens est sympa ici.", "Les gens sont sympas ici.",
     "gens <b>恒为复数</b>，动词和形容词都要用复数。"),
    ("I think about it.", "Je pense de ça.", "J'y pense.",
     "penser <b>à</b> = 想着某事（代词用 y）；penser <b>de</b> = 对某事的评价。"),
    ("I need it.", "J'ai besoin le.", "J'en ai besoin.",
     "avoir besoin <b>de</b> → 用代词 <b>en</b> 替代 de + 名词。"),
    ("She is a teacher.", "Elle est une professeure.", "Elle est professeure.",
     "être + 职业时<b>不加冠词</b>（除非带形容词修饰）。"),
    ("I miss you.", "Je te manque.", "Tu me manques.",
     "manquer 的主宾<b>与英语相反</b>：被思念的人做主语。"),
    ("Last year I went to France.", "L'année dernière j'ai allé en France.",
     "L'année dernière je suis allé(e) en France.",
     "aller 用 <b>être</b> 作助动词，过去分词要与主语性数配合。"),
]

# ---------------------------------------------------------------------------
# 05 · 高频介词搭配
# ---------------------------------------------------------------------------
PREPOSITIONS = [
    ("dépendre <b>de</b>", "depend <b>on</b>", "Ça dépend **de** toi.", "这取决于你。"),
    ("s'intéresser <b>à</b>", "be interested <b>in</b>", "Je m'intéresse **à** l'histoire.", "我对历史感兴趣。"),
    ("se souvenir <b>de</b>", "remember（无介词）", "Je me souviens **de** ce jour.", "我记得那一天。"),
    ("jouer <b>à</b>（运动/游戏）", "play", "Il joue **au** football.", "他踢足球。"),
    ("jouer <b>de</b>（乐器）", "play", "Elle joue **du** piano.", "她弹钢琴。"),
    ("participer <b>à</b>", "participate <b>in</b>", "Nous participons **à** ce projet.", "我们参与这个项目。"),
    ("répondre <b>à</b>", "answer（无介词）", "Réponds **à** ma question.", "回答我的问题。"),
    ("téléphoner <b>à</b>", "phone（无介词）", "Je téléphone **à** ma mère.", "我给我妈打电话。"),
    ("obéir <b>à</b>", "obey（无介词）", "Il faut obéir **aux** règles.", "必须遵守规则。"),
    ("ressembler <b>à</b>", "resemble（无介词）", "Tu ressembles **à** ton père.", "你长得像你爸。"),
    ("réussir <b>à</b>", "succeed <b>in</b>", "J'ai réussi **à** le convaincre.", "我成功说服了他。"),
    ("se moquer <b>de</b>", "make fun <b>of</b>", "Ne te moque pas **de** moi.", "别取笑我。"),
    ("avoir besoin <b>de</b>", "need（无介词）", "J'ai besoin **d'**aide.", "我需要帮助。"),
    ("s'occuper <b>de</b>", "take care <b>of</b>", "Je m'occupe **des** enfants.", "我照看孩子。"),
    ("changer <b>de</b>", "change（无介词）", "Je vais changer **de** travail.", "我要换工作。"),
    ("servir <b>à</b>（用途）", "be used <b>for</b>", "Ça sert **à** quoi ?", "这是干什么用的？"),
    ("penser <b>à</b>（想着）", "think <b>about/of</b>", "Je pense **à** toi.", "我想着你。"),
    ("rêver <b>de</b>", "dream <b>of/about</b>", "Je rêve **de** partir.", "我梦想着离开。"),
]

# ---------------------------------------------------------------------------
# 06 · 英法后缀换算公式
# ---------------------------------------------------------------------------
SUFFIX_RULES = [
    ("英语 <b>-tion / -sion</b> → 法语？", "<b>-tion / -sion</b>（名词 · 阴性 ♀）",
     "information → <i>l'information</i>；decision → <i>la décision</i>"),
    ("英语 <b>-ty</b> → 法语？", "<b>-té</b>（名词 · 阴性 ♀）",
     "university → <i>l'université</i>；liberty → <i>la liberté</i>；quality → <i>la qualité</i>"),
    ("英语副词 <b>-ly</b> → 法语？", "<b>-ment</b>（副词）",
     "rapidly → <i>rapidement</i>；normally → <i>normalement</i>"),
    ("英语 <b>-ous</b> → 法语？", "<b>-eux / -euse</b>（形容词）",
     "dangerous → <i>dangereux / dangereuse</i>；curious → <i>curieux / curieuse</i>"),
    ("英语 <b>-ic / -ical</b> → 法语？", "<b>-ique</b>（形容词 · 阴阳性同形）",
     "economic → <i>économique</i>；logical → <i>logique</i>"),
    ("英语 <b>-ary</b> → 法语？", "<b>-aire</b>（形容词 · 阴阳性同形）",
     "necessary → <i>nécessaire</i>；ordinary → <i>ordinaire</i>"),
    ("英语施事 <b>-or / -er</b> → 法语？", "<b>-eur</b>（名词 ♂ · 阴性多为 -euse / -rice）",
     "actor → <i>l'acteur / l'actrice</i>；director → <i>le directeur / la directrice</i>"),
    ("英语 <b>-ism / -ist</b> → 法语？", "<b>-isme</b>（名词 ♂）/ <b>-iste</b>（阴阳同形）",
     "capitalism → <i>le capitalisme</i>；artist → <i>un(e) artiste</i>"),
    ("英语 <b>-ance / -ence</b> → 法语？", "<b>-ance / -ence</b>（名词 · 阴性 ♀）",
     "importance → <i>l'importance</i>；difference → <i>la différence</i>"),
    ("英语动词 <b>-ate</b> → 法语？", "<b>-er</b>（第1组动词）",
     "create → <i>créer</i>；participate → <i>participer</i>；communicate → <i>communiquer</i>"),
    ("英语 <b>-ize / -ise</b> → 法语？", "<b>-iser</b>（第1组动词）",
     "organize → <i>organiser</i>；realize → <i>réaliser</i>"),
    ("英语 <b>-ment</b> → 法语？", "<b>-ment</b>（名词 · 阳性 ♂）",
     "government → <i>le gouvernement</i>；movement → <i>le mouvement</i>"),
    ("英语 <b>-ive</b> → 法语？", "<b>-if / -ive</b>（形容词）",
     "active → <i>actif / active</i>；positive → <i>positif / positive</i>"),
    ("英语 <b>-phy / -logy</b> → 法语？", "<b>-phie / -logie</b>（名词 · 阴性 ♀）",
     "philosophy → <i>la philosophie</i>；biology → <i>la biologie</i>"),
    ("英语 <b>-sis</b> → 法语？", "<b>-se</b>（名词 · 阴性 ♀）",
     "analysis → <i>l'analyse</i>；crisis → <i>la crise</i>"),
    ("英语 <b>-al</b> → 法语？", "<b>-el / -al</b>（形容词 · -al 复数为 -aux）",
     "natural → <i>naturel / naturelle</i>；national → <i>national</i>（pl. nationaux）"),
]

# ---------------------------------------------------------------------------
# 07 · 拼写侦探规则（字段：法语 / 英语 / 规则 / 语法细节）
# ---------------------------------------------------------------------------
SPELLING_RULES = [
    ("la forêt", "forest", "ˆ = 丢失的 s", "n.f. · 复数 des forêts"),
    ("l'hôpital", "hospital", "ˆ = 丢失的 s", "n.m. · <b>复数 les hôpitaux</b>"),
    ("l'île", "isle / island", "ˆ = 丢失的 s", "n.f. · 复数 des îles"),
    ("le château", "castle（chasteau）", "ˆ = 丢失的 s", "n.m. · <b>复数 les châteaux</b>"),
    ("le coût", "cost", "ˆ = 丢失的 s", "n.m. · 动词 coûter"),
    ("la bête", "beast", "ˆ = 丢失的 s", "n.f. · 也作形容词「蠢的」"),
    ("le maître", "master", "ˆ = 丢失的 s", "n.m. · 阴性 la maîtresse"),
    ("la tempête", "tempest", "ˆ = 丢失的 s", "n.f. · 复数 des tempêtes"),
    ("honnête", "honest", "ˆ = 丢失的 s", "adj. · 阴阳性同形"),
    ("l'intérêt", "interest", "ˆ = 丢失的 s", "n.m. · 复数 des intérêts"),
    ("la conquête", "conquest", "ˆ = 丢失的 s", "n.f. · 动词 conquérir"),
    ("l'ancêtre", "ancestor", "ˆ = 丢失的 s", "n.m. · 复数 des ancêtres"),
    ("la fête", "feast / festival", "ˆ = 丢失的 s", "n.f. · 动词 fêter"),
    ("arrêter", "arrest（停止／逮捕）", "ˆ = 丢失的 s", "v. 第1组 · 助动词 avoir · p.p. arrêté"),
    ("le vêtement", "vestment（衣物）", "ˆ = 丢失的 s", "n.m. · 复数 des vêtements"),
    ("la croûte", "crust", "ˆ = 丢失的 s", "n.f. · 复数 des croûtes"),
    ("l'étudiant", "student", "词首 é- = 英语 s- + 辅音", "n.m. · 阴性 une étudiante"),
    ("l'école", "school", "词首 é- = 英语 s- + 辅音", "n.f. · 复数 des écoles"),
    ("l'état", "state", "词首 é- = 英语 s- + 辅音", "n.m. · l'État = 国家"),
    ("étrange", "strange", "词首 é- = 英语 s- + 辅音", "adj. · 阴阳性同形"),
    ("l'épice", "spice", "词首 é- = 英语 s- + 辅音", "n.f. · 复数 des épices"),
    ("l'éponge", "sponge", "词首 é- = 英语 s- + 辅音", "n.f. · 复数 des éponges"),
    ("établir", "establish", "词首 é- = 英语 s- + 辅音", "v. 第2组 · 助动词 avoir · p.p. établi"),
    ("l'épine", "spine / thorn", "词首 é- = 英语 s- + 辅音", "n.f. · 复数 des épines"),
    ("l'épouse", "spouse", "词首 é- = 英语 s- + 辅音", "n.f. · 阳性 l'époux"),
    ("écarlate", "scarlet", "词首 é- = 英语 s- + 辅音", "adj. · 阴阳性同形"),
    ("l'étoile", "star（拉丁 stella）", "词首 é- = 英语 s- + 辅音", "n.f. · 复数 des étoiles"),
    ("l'épaule", "shoulder（拉丁 spatula）", "词首 é- = 英语 s- + 辅音", "n.f. · 复数 des épaules"),
]

# ---------------------------------------------------------------------------
# 08 · 阴阳性词尾规则
# ---------------------------------------------------------------------------
GENDER_RULES = [
    ("-tion / -sion / -ssion", "f", "~99%", "la nation, la décision, la passion", ""),
    ("-té / -tié", "f", "~99%", "la liberté, la qualité, l'amitié", "le côté, l'été, le comité"),
    ("-ance / -ence", "f", "~95%", "la chance, la science, la différence", "le silence"),
    ("-ure", "f", "~95%", "la culture, la nature, la voiture", "le mur"),
    ("-ette", "f", "~99%", "la baguette, la cigarette", ""),
    ("-ie", "f", "~95%", "la vie, la biologie, la sortie", "le génie, le parapluie"),
    ("-esse", "f", "~99%", "la richesse, la vitesse, la jeunesse", ""),
    ("-ude / -ade", "f", "~95%", "l'habitude, la salade, la promenade", "le stade, le grade"),
    ("-eur（抽象名词）", "f", "常见", "la peur, la couleur, la douleur, la chaleur", "le bonheur, le malheur"),
    ("-ment", "m", "~99%", "le gouvernement, le moment, le bâtiment", "la jument（母马）"),
    ("-age", "m", "~90%", "le voyage, le fromage, le message",
     "<b>la plage, l'image, la page, la cage, la nage, la rage</b>"),
    ("-eau", "m", "~95%", "le bureau, le château, le bateau", "<b>l'eau ♀, la peau ♀</b>"),
    ("-isme", "m", "100%", "le capitalisme, le tourisme", ""),
    ("-oir", "m", "~95%", "le miroir, le devoir, le couloir", ""),
    ("-ier / -er", "m", "~95%", "le cahier, le quartier, le boulanger", "la mer, la cuiller"),
    ("-et / -on", "m", "~90%", "le paquet, le ballon, le bâton", "la maison, la raison, la façon"),
    ("-eur（施事者／机器）", "m", "~95%", "le professeur, le moteur, l'ordinateur", ""),
    ("英语外来词", "m", "~95%", "le week-end, le parking, le smartphone, le shopping", "la start-up"),
    ("语言名", "m", "100%", "le français, le chinois, l'anglais", ""),
    ("星期／月份／季节", "m", "100%", "le lundi, le mai, l'été, l'hiver", ""),
    ("树／金属／颜色／数字", "m", "~100%", "le chêne, le fer, le vert, le trois", ""),
]

# ---------------------------------------------------------------------------
# 09 · 高频核心词（英语无同源，你的英语优势在这里完全失效）
# ---------------------------------------------------------------------------
CORE_WORDS = [
    # ===== 动词 =====
    dict(fr="rester", pos="v.",
         gram="第1组 -er · <b>助动词 être</b> · p.p. resté(e)(s) · je reste, nous restons",
         en="to stay, to remain, to be left", zh="停留、剩下",
         ex="Il **reste** encore du temps.", exzh="还有时间。"),
    dict(fr="chercher", pos="v.",
         gram="第1组 -er · 助动词 avoir · p.p. cherché · <b>直接及物，不加 pour</b>",
         en="to look for, to search", zh="找、寻找",
         ex="Je **cherche** mes lunettes.", exzh="我在找我的眼镜。"),
    dict(fr="trouver", pos="v.",
         gram="第1组 -er · 助动词 avoir · p.p. trouvé · je trouve que… = 我觉得……",
         en="to find; to think (opinion)", zh="找到；觉得",
         ex="Je **trouve** ça bizarre.", exzh="我觉得这很奇怪。"),
    dict(fr="garder", pos="v.", gram="第1组 -er · 助动词 avoir · p.p. gardé",
         en="to keep; to look after", zh="保留、保管；照看",
         ex="**Garde** ça pour toi.", exzh="这事你别说出去。"),
    dict(fr="laisser", pos="v.",
         gram="第1组 -er · 助动词 avoir · p.p. laissé · laisser qn faire qch",
         en="to leave (sth); to let", zh="留下；让、允许",
         ex="**Laisse**-moi t'expliquer.", exzh="让我跟你解释。"),
    dict(fr="apporter", pos="v.",
         gram="第1组 -er · 助动词 avoir · p.p. apporté · <b>用于物</b>（人用 amener）",
         en="to bring (an object)", zh="带来（物）",
         ex="**Apporte** ton ordinateur.", exzh="把你电脑带来。"),
    dict(fr="emmener", pos="v.",
         gram="第1组 -er · 助动词 avoir · p.p. emmené · <b>j'emmène</b>, nous emmenons（e→è）· 用于人",
         en="to take (a person) somewhere", zh="带走（人）",
         ex="Je t'**emmène** au restaurant.", exzh="我带你去餐厅。"),
    dict(fr="essayer", pos="v.",
         gram="第1组 -er · 助动词 avoir · p.p. essayé · <b>j'essaie</b>（或 j'essaye）· essayer <b>de</b> + inf.",
         en="to try; to try on", zh="尝试；试穿",
         ex="**Essaie** encore une fois.", exzh="再试一次。"),
    dict(fr="oublier", pos="v.",
         gram="第1组 -er · 助动词 avoir · p.p. oublié · oublier <b>de</b> + inf.",
         en="to forget", zh="忘记",
         ex="J'ai **oublié** mon parapluie.", exzh="我忘带伞了。"),
    dict(fr="tomber", pos="v.", gram="第1组 -er · <b>助动词 être</b> · p.p. tombé(e)(s)",
         en="to fall", zh="掉落、跌倒",
         ex="Elle est **tombée** dans l'escalier.", exzh="她在楼梯上摔倒了。"),
    dict(fr="jeter", pos="v.",
         gram="第1组 -er · 助动词 avoir · p.p. jeté · <b>je jette</b>, nous jetons（双写 tt）",
         en="to throw, to throw away", zh="扔、丢弃",
         ex="Ne **jette** pas ça !", exzh="别把这个扔了！"),
    dict(fr="ranger", pos="v.",
         gram="第1组 -er · 助动词 avoir · p.p. rangé · <b>nous rangeons</b>（g→ge 保软音）",
         en="to tidy up, to put away", zh="整理、收好",
         ex="**Range** ta chambre.", exzh="把你房间收拾一下。"),
    dict(fr="allumer", pos="v.", gram="第1组 -er · 助动词 avoir · p.p. allumé · 反义 éteindre",
         en="to turn on, to light", zh="打开（灯、电器）、点燃",
         ex="**Allume** la lumière, s'il te plaît.", exzh="请把灯打开。"),
    dict(fr="éteindre", pos="v.",
         gram="第3组 · 助动词 avoir · p.p. <b>éteint</b> · j'éteins, nous éteignons",
         en="to turn off, to extinguish", zh="关掉（灯、电器）、熄灭",
         ex="**Éteins** la lumière en sortant.", exzh="出去时把灯关了。"),
    dict(fr="gagner", pos="v.", gram="第1组 -er · 助动词 avoir · p.p. gagné",
         en="to win; to earn", zh="赢；赚",
         ex="Elle **gagne** bien sa vie.", exzh="她收入不错。"),
    dict(fr="choisir", pos="v.",
         gram="<b>第2组 -ir</b> · 助动词 avoir · p.p. choisi · je choisis, <b>nous choisissons</b>",
         en="to choose", zh="选择",
         ex="Il faut **choisir** maintenant.", exzh="现在必须做选择。"),
    dict(fr="empêcher", pos="v.",
         gram="第1组 -er · 助动词 avoir · p.p. empêché · empêcher qn <b>de</b> + inf.",
         en="to prevent, to stop (sb from)", zh="阻止、妨碍",
         ex="Rien ne t'**empêche** d'essayer.", exzh="没什么能阻止你去试。"),
    dict(fr="éviter", pos="v.",
         gram="第1组 -er · 助动词 avoir · p.p. évité · éviter <b>de</b> + inf.",
         en="to avoid", zh="避免",
         ex="J'**évite** les heures de pointe.", exzh="我避开高峰时段。"),
    dict(fr="atteindre", pos="v.",
         gram="第3组 · 助动词 avoir · p.p. <b>atteint</b> · j'atteins, nous atteignons",
         en="to reach, to attain", zh="达到、抵达",
         ex="Nous avons **atteint** notre objectif.", exzh="我们达到了目标。"),
    dict(fr="gérer", pos="v.",
         gram="第1组 -er · 助动词 avoir · p.p. géré · <b>je gère</b>, nous gérons（é→è）",
         en="to manage, to handle", zh="管理、处理",
         ex="Je **gère** la situation.", exzh="我来处理这个情况。"),
    dict(fr="plaire (à)", pos="v.",
         gram="第3组 · 助动词 avoir · p.p. <b>plu</b> · il plaît · <b>主宾与英语相反</b>：ça me plaît = 我喜欢它",
         en="to please, to be liked by", zh="使喜欢（主宾与英语相反）",
         ex="Ce film m'a beaucoup **plu**.", exzh="我很喜欢这部电影。"),
    dict(fr="manquer (à)", pos="v.",
         gram="第1组 -er · 助动词 avoir · p.p. manqué · <b>主宾与英语相反</b>：tu me manques = 我想你",
         en="to be missed by; to lack", zh="思念（主宾相反）；缺少",
         ex="Tu me **manques**.", exzh="我想你。"),
    dict(fr="suffire", pos="v.",
         gram="第3组 · 助动词 avoir · p.p. suffi · 常用无人称 <b>il suffit de</b> + inf.",
         en="to be enough, to suffice", zh="足够",
         ex="Ça **suffit** !", exzh="够了！"),
    dict(fr="se débrouiller", pos="v.pron.",
         gram="代动词 · 第1组 · <b>助动词 être</b> · p.p. débrouillé(e)(s) · je me débrouille",
         en="to manage, to cope, to get by", zh="自己应付、想办法",
         ex="Je me **débrouille** en français.", exzh="我法语还应付得来。"),
    dict(fr="se rendre compte (de)", pos="v.pron.",
         gram="代动词 · 助动词 être · <b>p.p. rendu 不作性数配合</b>（elle s'est rendu compte）",
         en="to realize", zh="意识到",
         ex="Je ne m'étais pas **rendu compte**.", exzh="我之前没意识到。"),
    dict(fr="falloir (il faut)", pos="v.imp.",
         gram="<b>无人称动词，只有 il 形式</b> · 助动词 avoir · p.p. fallu · il faut / il faudra / il fallait",
         en="to be necessary, must", zh="必须、需要",
         ex="Il **faut** partir maintenant.", exzh="现在必须走了。"),
    dict(fr="valoir (ça vaut)", pos="v.",
         gram="第3组 · 助动词 avoir · p.p. valu · il vaut · <b>il vaut mieux</b> + inf. = 最好……",
         en="to be worth", zh="值得、价值",
         ex="Ça **vaut** le coup.", exzh="这值得一试。"),
    dict(fr="s'agir (il s'agit de)", pos="v.imp.",
         gram="<b>无人称代动词，只有 il 形式</b> · 助动词 être · 不能用人做主语",
         en="to be about, to be a matter of", zh="涉及、关于",
         ex="Il **s'agit** d'un malentendu.", exzh="这是个误会。"),
    dict(fr="appartenir (à)", pos="v.",
         gram="第3组（tenir 型）· 助动词 avoir · p.p. appartenu · j'appartiens, nous appartenons",
         en="to belong to", zh="属于",
         ex="Ce livre **appartient** à Marie.", exzh="这本书是玛丽的。"),
    # ===== 副词 / 连接词 =====
    dict(fr="encore", pos="adv.", gram="pas encore = 还没 · encore une fois = 再一次",
         en="still; again; more", zh="还、仍然；再；更",
         ex="Tu es **encore** là ?", exzh="你还在这儿？"),
    dict(fr="déjà", pos="adv.", gram="常与复合过去时连用 · 疑问句表「已经……了吗」",
         en="already", zh="已经",
         ex="J'ai **déjà** mangé.", exzh="我已经吃过了。"),
    dict(fr="plutôt", pos="adv.", gram="plutôt que = 而不是 · <b>注意与 plus tôt（更早）区分</b>",
         en="rather, quite; instead", zh="宁可、相当；而是",
         ex="C'est **plutôt** difficile.", exzh="这相当难。"),
    dict(fr="quand même", pos="loc.", gram="口语极高频 · 更正式的同义词 tout de même",
         en="still, anyway, all the same", zh="还是、仍然",
         ex="C'est cher, mais je le prends **quand même**.", exzh="有点贵，但我还是买。"),
    dict(fr="d'ailleurs", pos="loc.", gram="补充一个附加论点 · 句首常见",
         en="besides, by the way, moreover", zh="再说、顺便一提",
         ex="**D'ailleurs**, je voulais t'en parler.", exzh="再说，我本来就想跟你聊这个。"),
    dict(fr="du coup", pos="loc.", gram="<b>口语</b>极高频 · 书面语请用 par conséquent / donc",
         en="so, as a result (colloquial)", zh="结果、于是",
         ex="Il pleuvait, **du coup** on est restés.", exzh="下雨了，结果我们就没走。"),
    dict(fr="désormais", pos="adv.", gram="<b>书面语</b> · 口语用 à partir de maintenant",
         en="from now on, henceforth", zh="从今以后",
         ex="**Désormais**, tout sera différent.", exzh="从今以后一切都会不同。"),
    dict(fr="toutefois", pos="adv.", gram="<b>书面语</b>转折 · 位置灵活 · B2 写作常用",
         en="however, nevertheless", zh="然而",
         ex="Ce projet est ambitieux ; **toutefois**, il reste réalisable.",
         exzh="这个项目雄心勃勃，然而仍然可行。"),
    dict(fr="néanmoins", pos="adv.", gram="<b>书面语</b>让步转折 · <b>B2 议论文必备</b>",
         en="nevertheless, nonetheless", zh="尽管如此",
         ex="Les résultats sont modestes ; **néanmoins**, ils sont encourageants.",
         exzh="结果不算显著，但仍令人鼓舞。"),
    dict(fr="en revanche", pos="loc.", gram="表对比 · 同义 par contre（口语更常用）",
         en="on the other hand, by contrast", zh="相反、另一方面",
         ex="Le prix est élevé ; **en revanche**, la qualité est excellente.",
         exzh="价格偏高，但质量极好。"),
    dict(fr="or", pos="conj.",
         gram="<b>论证转折词</b>，置于句首 · 引出改变前提的新事实 · B2 阅读高频",
         en="now, yet (introduces a turn in the argument)", zh="然而、可是",
         ex="Tout semblait réglé. **Or**, un problème est apparu.",
         exzh="一切似乎都解决了。然而，一个问题出现了。"),
    dict(fr="certes", pos="adv.",
         gram="<b>让步开场</b> · 固定套路 Certes…, mais… · <b>B2 议论文必备</b>",
         en="admittedly, granted", zh="诚然、固然",
         ex="**Certes**, c'est coûteux, mais c'est nécessaire.",
         exzh="诚然这很贵，但很有必要。"),
    dict(fr="en effet", pos="loc.",
         gram="用于<b>印证或解释</b>前一句 · 注意：转折的「其实」是 en fait，两者不同",
         en="indeed, in fact (confirms or explains)", zh="确实、事实上",
         ex="Il n'est pas venu ; **en effet**, il était malade.",
         exzh="他没来；事实上他病了。"),
    dict(fr="voire", pos="adv.", gram="<b>书面语</b>递进 · 勿与动词 voir（看）混淆",
         en="or even, indeed", zh="甚至",
         ex="C'est difficile, **voire** impossible.", exzh="这很难，甚至不可能。"),
    dict(fr="tandis que", pos="conj.", gram="引导从句 + <b>直陈式</b> · 表对比或同时",
         en="whereas, while", zh="而、与此同时",
         ex="Il travaille, **tandis que** son frère s'amuse.", exzh="他在工作，而他弟弟在玩。"),
    dict(fr="alors que", pos="conj.", gram="引导从句 + <b>直陈式</b> · 表对比或让步",
         en="whereas; even though", zh="尽管、而",
         ex="Il est sorti **alors qu'**il pleuvait.", exzh="尽管下着雨他还是出门了。"),
    dict(fr="dès que", pos="conj.", gram="+ <b>直陈式</b> · 谈将来时主从句<b>都用将来时</b>",
         en="as soon as", zh="一……就……",
         ex="Appelle-moi **dès que** tu arrives.", exzh="你一到就给我打电话。"),
    dict(fr="afin de / afin que", pos="loc.",
         gram="afin <b>de</b> + 不定式（同主语）· afin <b>que</b> + <b>虚拟式</b>（不同主语）",
         en="in order to / so that", zh="为了",
         ex="Il travaille dur **afin de** réussir.", exzh="他努力工作以求成功。"),
    dict(fr="sinon", pos="conj.", gram="引出反面后果 · 口语书面皆可",
         en="otherwise, or else", zh="否则",
         ex="Dépêche-toi, **sinon** on va être en retard.", exzh="快点，否则我们要迟到了。"),
    dict(fr="autant", pos="adv.", gram="autant de + 名词 · autant que = 和……一样多",
         en="as much, so much", zh="同样多、如此多",
         ex="Je n'ai jamais **autant** travaillé.", exzh="我从没这么努力过。"),
    dict(fr="tellement", pos="adv.", gram="tellement de + 名词 · tellement… que = 如此……以至于",
         en="so, so much", zh="如此、这么",
         ex="Il fait **tellement** chaud !", exzh="太热了！"),
    dict(fr="à peine", pos="loc.", gram="句首时常引起<b>倒装</b>：À peine était-il arrivé que…",
         en="hardly, barely", zh="几乎不、刚刚",
         ex="Je l'ai **à peine** vu.", exzh="我几乎没看见他。"),
    # ===== 名词 =====
    dict(fr="un truc", pos="n.m.", gram="复数 des trucs · <b>口语</b>万能词，正式场合勿用",
         en="thing, thingy", zh="东西、玩意儿",
         ex="C'est quoi ce **truc** ?", exzh="这是什么玩意儿？"),
    dict(fr="un endroit", pos="n.m.", gram="复数 des endroits · 同义 un lieu（更正式）",
         en="place, spot", zh="地方",
         ex="C'est un **endroit** magnifique.", exzh="这地方真美。"),
    dict(fr="le milieu", pos="n.m.",
         gram="<b>复数 les milieux</b>（-eu → -eux）· au milieu de = 在……中间",
         en="middle; environment, circle", zh="中间；环境、圈子",
         ex="Il s'est réveillé au **milieu** de la nuit.", exzh="他半夜醒了。"),
    dict(fr="la plupart (de)", pos="n.f.",
         gram="<b>la plupart des + 复数名词 → 动词用复数</b>（la plupart des gens <b>sont</b>…）",
         en="most (of)", zh="大部分",
         ex="**La plupart** des gens sont d'accord.", exzh="大部分人都同意。"),
    dict(fr="un souci", pos="n.m.", gram="复数 des soucis · 口语 pas de souci = 没问题",
         en="worry, problem", zh="烦恼、问题",
         ex="Pas de **souci** !", exzh="没问题！"),
    dict(fr="le boulot", pos="n.m.", gram="复数 des boulots · <b>口语</b> · 正式用 le travail",
         en="job, work (colloquial)", zh="工作（口语）",
         ex="J'ai beaucoup de **boulot**.", exzh="我活儿很多。"),
    # ===== 形容词 / 限定词 =====
    dict(fr="chaque / chacun", pos="adj. / pron.",
         gram="chaque + <b>单数名词</b>（无复数形式）· chacun(e) 是代词，独立使用",
         en="each / each one", zh="每个／每一个",
         ex="**Chacun** fait ce qu'il veut.", exzh="各人做各人的事。"),
    dict(fr="pareil / pareille", pos="adj.", gram="<b>阴性 pareille</b> · 复数 pareils / pareilles",
         en="the same, similar", zh="一样的",
         ex="C'est **pareil** pour moi.", exzh="对我来说都一样。"),
    dict(fr="propre", pos="adj.",
         gram="阴阳性同形 · <b>位置改变词义</b>：sa <b>propre</b> voiture 他自己的车 / une voiture <b>propre</b> 干净的车",
         en="(before noun) own; (after noun) clean", zh="（前置）自己的；（后置）干净的",
         ex="Il a sa **propre** entreprise.", exzh="他有自己的公司。"),
    dict(fr="épais / épaisse", pos="adj.", gram="<b>阴性 épaisse</b> · 复数 épais（不变）/ épaisses",
         en="thick", zh="厚的",
         ex="C'est un livre très **épais**.", exzh="这是本很厚的书。"),
    dict(fr="lourd / lourde", pos="adj.", gram="阴性 lourde · 反义 léger / légère",
         en="heavy", zh="重的",
         ex="Ce sac est trop **lourd**.", exzh="这包太重了。"),
    dict(fr="léger / légère", pos="adj.", gram="<b>阴性 légère</b>（é→è）· 复数 légers / légères",
         en="light (in weight); slight", zh="轻的；轻微的",
         ex="Prends un sac plus **léger**.", exzh="拿个轻一点的包。"),
    dict(fr="vide", pos="adj.", gram="阴阳性同形 · 复数 vides · 反义 plein / pleine",
         en="empty", zh="空的",
         ex="La salle est presque **vide**.", exzh="大厅几乎是空的。"),
    dict(fr="plein / pleine", pos="adj.", gram="阴性 pleine · 口语 plein de = 很多",
         en="full", zh="满的",
         ex="Il y a **plein** de monde.", exzh="人很多。"),
    dict(fr="doux / douce", pos="adj.", gram="<b>阴性 douce</b> · 复数 doux（不变）/ douces",
         en="soft, gentle, mild, sweet", zh="柔和的、温和的",
         ex="Elle a une voix très **douce**.", exzh="她的声音很温柔。"),
    # ===== 惯用表达 =====
    dict(fr="n'importe quoi", pos="expr.",
         gram="系列：n'importe qui / où / quand / comment · 口语常表「胡扯」",
         en="nonsense; anything at all", zh="胡说八道；随便什么",
         ex="Tu dis **n'importe quoi** !", exzh="你在胡说八道！"),
    dict(fr="ça marche", pos="expr.", gram="<b>口语</b> · 表示同意，或表示「行得通」",
         en="it works; OK, deal", zh="行、可以",
         ex="On se voit à huit heures ? — **Ça marche** !", exzh="八点见？——行！"),
    dict(fr="en fait", pos="expr.",
         gram="<b>这才是英语的 actually</b>，不是 actuellement · 口语极高频",
         en="actually, in fact", zh="其实、实际上",
         ex="**En fait**, je ne savais pas.", exzh="其实我并不知道。"),
    dict(fr="c'est-à-dire", pos="expr.", gram="缩写 c.-à-d. · 用于解释或改述",
         en="that is to say, i.e.", zh="也就是说",
         ex="Demain, **c'est-à-dire** lundi.", exzh="明天，也就是周一。"),
]
